import streamlit as st
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.cluster import DBSCAN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import RobustScaler

# --- PAGE CONFIG ---
st.set_page_config(page_title="Phishing Detection AI", layout="wide")

@st.cache_resource
def load_and_train_models():
    # 1. Load dataset
    try:
        df = pd.read_csv('StealthPhisher_mini.csv') 
    except FileNotFoundError:
        df = pd.read_csv('StealthPhisher2025.csv')

    # 2. Select ONLY the highly crucial features controlled by the UI
    ui_features = ['ShannonEntropy', 'NumberOfSubdomains', 'IsFormSubmitExternal', 'IsDomainIP']
    
    # Ensure columns exist to prevent crashes
    available_features = [f for f in ui_features if f in df.columns]
    if not available_features:
        raise ValueError("None of the critical features were found in the CSV!")
        
    features_only = df[available_features]
    
    # 3. Scale the data
    scaler = RobustScaler()
    X_scaled = scaler.fit_transform(features_only)

    # 4. Train Isolation Forest
    iso_forest = IsolationForest(contamination=0.15, random_state=42)
    iso_forest.fit(X_scaled)
    
    # 5. Train DBSCAN & KNN Proxy (For Real-Time UI Prediction)
    dbscan = DBSCAN(eps=8.5, min_samples=64)
    clusters = dbscan.fit_predict(X_scaled)
    
    knn_proxy = KNeighborsClassifier(n_neighbors=5)
    knn_proxy.fit(X_scaled, clusters)
    
    # 6. Create Baseline for UI Input
    baseline = features_only.iloc[[0]].copy()
    baseline[available_features] = features_only[available_features].median().values
    
    return scaler, iso_forest, knn_proxy, baseline, available_features

# Initialize models
try:
    scaler, iso_model, db_model, baseline_template, active_features = load_and_train_models()
except Exception as e:
    st.error(f" Deployment Error: {e}")
    st.stop()

# --- STREAMLIT UI ---
st.title(" Phishing Detection: Dual-Model Analysis")
st.write("Evaluating crucial email threat indicators by comparing **Isolation Forest** (Anomaly Detection) and **DBSCAN** (Density Clustering).")

st.sidebar.header("Test Email Features")

entropy = st.sidebar.slider(
    "Shannon Entropy (Gibberish Level)", 
    min_value=0.0, max_value=8.0, value=3.5, step=0.1, 
    help="Higher values indicate random, unreadable URLs often generated by attackers."
)

subdomains = st.sidebar.number_input(
    "Number of Subdomains", 
    min_value=0, max_value=15, value=0, 
    help="Phishing sites often bury the real domain under many fake ones."
)

external_form = st.sidebar.radio(
    "Does the page submit forms externally?", 
    options=["No", "Yes"], 
    index=0, 
    help="Malicious sites host fake logins that secretly send passwords to an external attacker server."
)
ext_form_val = 1 if external_form == "Yes" else 0

domain_ip = st.sidebar.radio(
    "Does the URL use an IP address?", 
    options=["No", "Yes"], 
    index=0, 
    help="Raw IP addresses (e.g., 192.168.1.1) in links are highly suspicious."
)
domain_ip_val = 1 if domain_ip == "Yes" else 0

# --- PREDICTION LOGIC ---
if st.button("Run AI Analysis"):
    # Prepare input
    input_df = baseline_template.copy()
    
    if 'ShannonEntropy' in active_features:
        input_df['ShannonEntropy'] = entropy
    if 'NumberOfSubdomains' in active_features:
        input_df['NumberOfSubdomains'] = subdomains
    if 'IsFormSubmitExternal' in active_features:
        input_df['IsFormSubmitExternal'] = ext_form_val
    if 'IsDomainIP' in active_features:
        input_df['IsDomainIP'] = domain_ip_val
    
    # Scale and Predict
    input_scaled = scaler.transform(input_df)
    
    # Format to 2D array to prevent shape errors
    if len(input_scaled.shape) == 1:
        input_scaled = input_scaled.reshape(1, -1)
        
    # --- 1. ISOLATION FOREST PREDICTION ---
    iso_res = iso_model.predict(input_scaled)[0]
    
    # --- 2. DBSCAN (KNN PROXY) PREDICTION WITH DISTANCE CHECK ---
    # Measure the exact distance to the nearest data point
    distances, indices = db_model.kneighbors(input_scaled, n_neighbors=1)
    nearest_distance = distances[0][0]
    
    # If it is further away than our DBSCAN eps (0.5), it is an anomaly
    if nearest_distance > 0.5:
        db_res = -1  # Force label as Noise/Phishing
    else:
        # Otherwise, let it vote normally
        db_res = db_model.predict(input_scaled)[0]
    
    # --- RESULTS UI ---
    st.divider()
    st.subheader("Real-Time Model Evaluation")
    
    col1, col2 = st.columns(2)
    
    # --- ISOLATION FOREST UI PANEL ---
    with col1:
        st.markdown("###  Isolation Forest")
        if iso_res == 1:
            st.success("**Verdict: LEGITIMATE**")
            st.write("The model considers these feature parameters to be within normal, safe bounds.")
        else:
            st.error("**Verdict: PHISHING (Anomaly)**")
            st.write("Threat detected! This model successfully isolated this email as a statistical anomaly.")

    # --- DBSCAN UI PANEL ---
    with col2:
        st.markdown("###  DBSCAN (Density)")
        if db_res != -1:
            st.success("**Verdict:  LEGITIMATE (Standard Cluster)**")
            st.write("Because this model relies on density, it incorrectly grouped this within a normal neighborhood.")
        else:
            st.error("**Verdict:  PHISHING (Noise/Outlier)**")
            st.write("Threat detected! The data point was far enough away to be classified as noise.")